# Generated by Django 4.2.21 on 2025-05-22 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=20)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=50)),
                ('primary_color', models.CharField(default='#1CA1C1', max_length=20)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=False)),
                ('notification_sound', models.BooleanField(default=True)),
                ('notification_vibration', models.BooleanField(default=True)),
                ('notification_light', models.BooleanField(default=True)),
                ('profile_pic_visibility', models.CharField(default='everyone', max_length=20)),
                ('profile_pic_download', models.CharField(default='everyone', max_length=20)),
                ('account_privacy', models.CharField(default='public', max_length=20)),
                ('connection_requests', models.CharField(default='everyone', max_length=20)),
                ('search_engine_visibility', models.BooleanField(default=True)),
                ('third_party_access', models.BooleanField(default=False)),
                ('active_status_visibility', models.BooleanField(default=True)),
                ('profile_view_tracking', models.BooleanField(default=True)),
                ('data_retention', models.CharField(default='1_month', max_length=20)),
                ('data_export', models.CharField(default='full', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
